version: '3.8'

services:
  youtube-archiver:
    build: .
    container_name: youtube-archiver
    ports:
      - "8899:8899"
    volumes:
      - ./config:/app/config
      - ./youtube_archive:/app/youtube_archive
    restart: unless-stopped
    environment:
      - TZ=Australia/Sydney
